
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Use a dummy DATABASE_URL during build if not set (prisma generate doesn't need a real connection)
// prisma generate only needs the schema file, not an actual database connection
const databaseUrl = process.env.DATABASE_URL 
  ? env("DATABASE_URL") 
  : "postgresql://dummy:dummy@localhost:5432/dummy";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
